### ISSUE TITLE
Soldier doesnt have blast jump dmg resistance

### ISSUE THREAD

**Issue by qualitykk** [AmperSoftware/TF-Source-2-Issues#12]
**Describe the bug**
In TF2, soldier has a rocket jump damage reduction causing him to only take ~40 damage per rocket jump. However in tfs2 he always takes regular damage when blast jumping

**To Reproduce**
1. Select Soldier
2. Rocket Jump
3. You should take ~60 damage

**Expected behavior**
You should be taking ~40 damage

**Comment by MoonlyDays** [comment]
Should be fixed when `damage` branch is merged.
