### ISSUE TITLE
Refilling at Ammo Station in spawn destroys sticky bombs

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#17]
**Describe the bug**
Refilling at spawn will destroy any sticky bombs placed by Demoman.

**To Reproduce**
1. Go to any map
2. Pick Demo and shoot stickies
3. Refill at spawn, stickies are gone

**Expected behavior**
Sticky bombs should persist unless Sticky Launcher is replaced. (has been confirmed to be true behavior in TF2)

**Comment by MoonlyDays** [comment]
Should be fixed. Now we're only recreating weapon if player changed it with their loadout.
