### ISSUE TITLE
Medic viewmodel arms

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#18]
**Describe the bug**
Medic viewmodel arms are weird looking and distorted, it's probably a placeholder model but nonetheless.

**To Reproduce**
1. Go to any map
2. Pick Medic
3. Witness

**Expected behavior**
Should match TF2 (or surpass)

**Screenshots**

![image](https://user-images.githubusercontent.com/41569944/162089371-0f762020-016a-4af3-ae9c-203a654fa71b.png)

**Comment by justynboi** [comment]
Broken because when the medic player model got remade, but no one ever updated the arms for the viewmodel. I will fix this later.

**Comment by justynboi** [comment]
Fixed! Will push the fix very soon

![image](https://user-images.githubusercontent.com/17112771/162096079-5b9a635a-689d-4cca-96f1-cd5ca87f3cae.png)
