### ISSUE TITLE
Medic syringes collide with skybox

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#19]
**Describe the bug**
Medic syringes are stopped by the skybox, creating dust and colliding with it.

**To Reproduce**
1. Go to any map with skybox
2. Pick Medic and shoot syringes at the skybox
3. They should be stuck

**Expected behavior**
Should fly through the skybox and be destroyed out of bounds (or just collide there and vanish afterwards)

**Screenshots**

![image](https://user-images.githubusercontent.com/41569944/162089579-b5cf2692-836e-42e9-9d49-c5d916d1d318.png)

**Comment by MoonlyDays** [comment]
Should be fixed next backend upload.
