### ISSUE TITLE
Ubercharge material

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#21]
**Describe the bug**

1. Ubercharge material does not apply to the weapon of the healed player.
2. Ubercharge material does not apply correctly to the medic itself.

**To Reproduce**
1. Use ubercharge in general

**Expected behavior**
Apply to weapons correctly and to the medic itself correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/41569944/162090888-bc7f357e-5ce5-43bc-86f1-83c80b3e1cc6.png)

**Comment by justynboi** [comment]
This is fixed
