### ISSUE TITLE
Healing beams persisting after death and resupply

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#22]
**Describe the bug**
Particle and actual healing persist from the last spot medigun was used in connected to the same player.

**To Reproduce**
1. Go to any map
2. Pick Medic, heal a player
3. Die or resupply
4. Beam persists

**Expected behavior**
Beam should be immediately destroyed upon resupply or player death.

**Screenshots**

![image](https://user-images.githubusercontent.com/41569944/162091701-93ae9422-9013-4c8a-83ca-0a525ff93dec.png)

**Comment by MoonlyDays** [comment]
This issue seems to be fixed now. Please retest it in the current backend upload and close the issue if you consider it to be fixed.
