### ISSUE TITLE
Uber active at 0% after resupply

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#24]
**Describe the bug**
Upon using uber, if resupplied, uber will be reset to 0% but will still grant uber to the player. (it is also infinite after that)

**To Reproduce**
1. Pick Medic
2. Get an uber and use it
3. While NOT healing the player, resupply and heal again
4. Player will be ubered

**Expected behavior**
Uber should completely vanish after resupply and do not apply to the players.

**Additional context**

https://user-images.githubusercontent.com/41569944/162092394-e5d593da-d09e-416f-b87c-e4ca8ce0a53b.mp4

**Comment by MoonlyDays** [comment]
Should be fixed when `damage` branch is merged.

**Comment by MoonlyDays** [comment]
This issue seems to be fixed now. Please retest it in the current backend upload and close the issue if you consider it to be fixed.
