### ISSUE TITLE
Rocket Launcher quick switch reload cancel

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#28]
**Describe the bug**
If you quick switch to other weapon when starting to reload your Rocket Launcher, it will cancel the animation, but rocket will be loaded, that way you just skip reloading.

**To Reproduce**
1. Shoot Rocket Launcher
2. Start reloading
3. Quickly switch to and from your other weapon
4. Rocket is loaded and you don't have to wait (you can as well shoot at that moment)

**Expected behavior**
Rocket loading should be cancelled with the animation at the same time.

**Additional context**

https://user-images.githubusercontent.com/41569944/162094545-c7392925-3a47-4662-832b-498a4358cc96.mp4

**Comment by justynboi** [comment]
This also happens with shotguns, pistols, scattergun, etc.

**Comment by MoonlyDays** [comment]
This issue seems to be fixed now. Please retest it in the current backend upload and close the issue if you consider it to be fixed.
