### ISSUE TITLE
Medics syringe projectile, when shot at certain objects, don't function properly.

### ISSUE THREAD

**Issue by Mynameongithub** [AmperSoftware/TF-Source-2-Issues#3]
**Describe the bug**
The syringes from Medic's gun shot at specifically the beam in the starting area of area well night stick sideways to the wall and spam the metal impact effect. This could lower framerate when done enough

**To Reproduce**
1. Open the game normally, select area well night as your map, play as medic, 
2. shoot the metal beam in start area
3. See the magic happen

**Expected behavior**
Well it aint supposed to do that, it should just shoot and stick the wall horizontally without all the fuss.

**Screenshots**

https://user-images.githubusercontent.com/102883540/161405703-f9a57d56-6f35-43a1-b350-af80d448f870.mp4

**Comment by MoonlyDays** [comment]
Should be fixed in next backend upload.
