### ISSUE TITLE
Demoman Eyelander (sword) animations are broken

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#34]
**Describe the bug**
Sword equip animation is completely broken and then attack, walk, hold, all of the animations are missing.

**To Reproduce**
1. Pick Demoman and equip Eyelander

**Expected behavior**
Should have complete and working animation set for eyelander and other swords in future.

**Comment by KayaDLX** [comment]
Will be implemented later once we get back to adding custom weapons.
