### ISSUE TITLE
Engineer PDA equip animation is broken

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#35]
**Describe the bug**
When you switch weapons to PDA and from PDA to others, there's a broken animation.

**To Reproduce**
1. Pick Engineer and switch to and from PDA

**Expected behavior**
Should have a fixed animation set for weapon switching.

**Comment by KayaDLX** [comment]
Fixed this in a recent commit, will be pushed live at a later time.
