### ISSUE TITLE
Fall damage sound playing excessivley

### ISSUE THREAD

**Issue by SlimesMcDingle** [AmperSoftware/TF-Source-2-Issues#37]
**Describe the bug**
When taking fall damage the sound plays 3 times within a very short amount of time.

**To Reproduce**
1. Go to a high place
2. Fall
3. See error

**Expected behavior**
It should just play the sound once.

**Screenshots**
![image](https://user-images.githubusercontent.com/102911470/162480880-cd4b89b0-f93e-40d8-a90e-bfc07b2dd195.png)

**Additional context**
I was on cp_domain, but I don't think that has anything to do with it. It was happening with all classes.

**Comment by SlimesMcDingle** [comment]
Upon further inspection, that console message shows up in threes every time you fall AT ALL, not just from taking fall damage.

**Comment by SlimesMcDingle** [comment]
Even weirder, it only says that when I land, but when others land it only says they landed once.

**Comment by MoonlyDays** [comment]
This was caused by frame simulated movement experiment, it was reverted so this should now be fixed.
