### ISSUE TITLE
Broken auto reload and console spam

### ISSUE THREAD

**Issue by SlimesMcDingle** [AmperSoftware/TF-Source-2-Issues#38]
**Describe the bug**
When turning off auto reload, it will spam the console after shooting and make you constantly play the reload animation, although your weapon won't actually reload. The issues stop when you press the reload key.

**To Reproduce**
1. Turn off auto reload in the options.
2. Pick any class that can reload.
3. Shoot your weapon

**Expected behavior**
It should just not reload, instead of playing the animation and spamming console

**Screenshots**
![image](https://user-images.githubusercontent.com/102911470/162482130-0fc02af1-748a-4c55-888e-bbc19b36303b.png)

**Comment by KayaDLX** [comment]
Can confirm, any chance you could look into it @qualitykk ?

**Comment by qualitykk** [comment]
Should be fixed in the next backend upload.
