### ISSUE TITLE
arena_well clip issue

### ISSUE THREAD

**Issue by SlimesMcDingle** [AmperSoftware/TF-Source-2-Issues#4]
**Describe the bug**
Not really a bug, but you can stand these 2 pillars on arena_well red side, bot not on blu side.

**To Reproduce**
1. Run map arena_well (daytime version, not sure about night).
2. Noclip or rocket jump on top of one of those pillars.
3. See error.
4. Profit.

**Expected behavior**
There shouldn't be any room to stand up there

**Screenshots**
![image](https://user-images.githubusercontent.com/102911470/161432489-04f8908b-1947-484d-9629-82e83c1306df.png)

**Comment by KayaDLX** [comment]
I'll have to do a full clipping check of this map because Valve never really properly clipped it, there's a few other places where you shouldn't be able to get on to.

**Comment by SlimesMcDingle** [comment]
Ah, I had thought you just recreated the geometry and then added your own clipping.

**Comment by KayaDLX** [comment]
Fixed, will be live once I compile the map again
