### ISSUE TITLE
Arena maps don't have functioning respawn rooms

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#42]
**Describe the bug**
Switching class in arena during setup will kill you without quick respawn in spawn. Resupply stations also do not work, as well as doors.

**To Reproduce**
1. Join _well_ map and check respawn room.

**Expected behavior**
Should have insta class switch during setup, working resupply station and working doors.

**Comment by KayaDLX** [comment]
Will be added next compile
