### ISSUE TITLE
Ammo boxes refill ammo in the clip

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#43]
**Describe the bug**
Ammo boxes refill missing part of weapon's magazine.

**To Reproduce**
1. Shoot a bit from any weapon and pickup ammo box without reloading.

**Expected behavior**
Ammo boxes should only add to the pool of weapon's spare ammo and only if IT is not full.

**Comment by MoonlyDays** [comment]
Should be fixed next backend upload.
