### ISSUE TITLE
UI overflow on Engineer's item selection screen

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#44]
**Describe the bug**
Engineer has more items than other characters and they do not fit in the given space.

**To Reproduce**
1. Open inventory and check Engineer.

**Expected behavior**
Should condense or otherwise fit all items in the given space.

**Screenshots**

![image](https://user-images.githubusercontent.com/41569944/162846736-4f092d13-e112-4ece-ab41-d4505801ac89.png)

**Comment by MoonlyDays** [comment]
Should be fixed when `damage` branch is merged.
