### ISSUE TITLE
BLU players spawn at wrong spawn room in Domain

### ISSUE THREAD

**Issue by pivotman319-owo** [AmperSoftware/TF-Source-2-Issues#46]
**Describe the bug**
All BLU team players in Domain are placed in the opposing team's spawn room at B, which opens up massive room for backcapping and infighting.

**To Reproduce**
1. gamemode amper.tfs2; map amper.cp_domain
2. Join BLU team
3. Pick a class

**Expected behavior**
The player should be placed in the correct spawn room

**Screenshots**
![Issue at hand](https://user-images.githubusercontent.com/15126754/162949618-b2e9c810-85a9-40f5-bda2-1fa4adafda2c.png)
https://cdn.discordapp.com/attachments/959820043221340220/963397419213672498/sbox_2022-04-12_13-11-51.mp4

**Additional context**
N/A

**Comment by pivotman319-owo** [comment]
> I just pushed the most up to date & stable branch to the backend, check if this still happens

didn't help, redownloaded domain and am running into the same issue:
![spawn room](https://user-images.githubusercontent.com/15126754/163420721-4e6965d0-26de-4a57-b2c9-9c87c811d7c2.png)

**Comment by KayaDLX** [comment]
Should be fixed now, latest changes are now on the backend again
