### ISSUE TITLE
Needles acting a bit funky in first person

### ISSUE THREAD

**Issue by SlimesMcDingle** [AmperSoftware/TF-Source-2-Issues#49]
**Is your feature request related to a problem? Please describe.**
You can see needles attached to your character in first person. In live tf2, needles don't show up in first person.

**Describe the solution you'd like**
Don't allow needles to appear if they have hit a player.

**Additional context**
![image](https://user-images.githubusercontent.com/102911470/163264270-036193b5-9b3e-4c77-a92f-26ce9440bcbb.png)

**Comment by uglycoal** [comment]
Needles are visible by other players in TF2. They're just not shown in first person along with the model.

**Comment by SlimesMcDingle** [comment]
yeah i edited it after realizing my silly little mistake

**Comment by MoonlyDays** [comment]
This issue seems to be fixed now. Please retest it in the current backend upload and close the issue if you consider it to be fixed.
