### ISSUE TITLE
Round start rocket jumping should be disabled somehow

### ISSUE THREAD

**Issue by SlimesMcDingle** [AmperSoftware/TF-Source-2-Issues#5]
**Is your feature request related to a problem? Please describe.**
When you start a match, it lets you walk around for a bit, and then it resets you back at the spawn point. During this stage, you can't WASD, but you can jump and rocket jump, meaning that you can rocket jump forward, contradicting the fact that you shouldn't be able to move at all.

**Describe the solution you'd like**
What should happen is that when the announcer yells "ARE YOU READY?!!!!", players shouldn't be able to jump or rocket blast away.

**Additional context**
I tried to add a video but it's too big, so I tried converting it to a gif but it ended up being 3x bigger ???

**Comment by KayaDLX** [comment]
tf_preround_push_from_damage_enable @MoonlyDays

**Comment by MoonlyDays** [comment]
Should be fixed when `damage` branch is merged.

**Comment by KayaDLX** [comment]
Command `tf_preround_push_from_damage_enable` has been added, closing
