### ISSUE TITLE
Stickybombs get deleted when it collides with a physics prop

### ISSUE THREAD

**Issue by HueyCan** [AmperSoftware/TF-Source-2-Issues#51]
**Describe the bug**
When a stickybomb hits a physics prop at the right angle, it gets deleted.

**To Reproduce**
1. Go to any map with any physics prop
2. Use the stickybomb launcher and shoot the physics prop at a certain angle (easier to preform with a larger prop)

**Expected behavior**
Stickybombs should have no interaction with physics props. It should simply not collide with physics props

**Comment by MoonlyDays** [comment]
Should be fixed when `damage` branch is merged.
