### ISSUE TITLE
Scoping while reloading should cancel rescope

### ISSUE THREAD

**Issue by gvarados1** [AmperSoftware/TF-Source-2-Issues#52]
### Describe the bug

If you fire a shot with the sniper rifle and try to toggle zoom while reloading, it won't toggle. You have to wait for the reload to finish before you can toggle zoom

### To Reproduce

1. Shoot sniper rifle
2. Toggle zoom immediately after
3. zoom doesn't toggle

### Expected behavior

zoom should toggle any time you press the zoom button

**Comment by MoonlyDays** [comment]
I checked this in live, and you cannot zoom while the reload is happening. This is intended behavior on the stock Sniper Rifle, unless i'm misunderstanding the issue.

**Comment by gvarados1** [comment]
The zoom bool doesn't toggle so you're forced to zoom in after reloading,
even if you try to unzoom during reload

**Comment by MoonlyDays** [comment]
For now set `cl_autorezoom` convar to 0. In the future it'll be configurable in the settings menu.
Note that convar changes don't persist between game sessions for now.

**Comment by MoonlyDays** [comment]
Nevermind, I watched the video without volume the first time. I see the issue now. Thank you for clarifying.

**Comment by MoonlyDays** [comment]
This issue seems to be fixed now. Please retest it in the current backend upload and close the issue if you consider it to be fixed.
