### ISSUE TITLE
Specating People Freezes them in place

### ISSUE THREAD

**Issue by RevolverSoftworks** [AmperSoftware/TF-Source-2-Issues#53]
### Describe the bug

whenever you go into spectator and view someone in first or third person view, it freeze them in place and they are unable to move at all. this works whether they are on the ground or in the air.

### To Reproduce

Go to Spectator Mode
Spectate Somebody
Result

### Expected behavior

The Player should not be stuck by spectators viewing them, as they should be able to move freely regardless of if anybody is viewing them or not, this could be due to collision being set wrong or something very similar.

**Comment by MoonlyDays** [comment]
This issue seems to be fixed now. Please retest it in the current backend upload and close the issue if you consider it to be fixed.
