### ISSUE TITLE
Rocket Jumper doesn't work and has normal explosion

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#6]
**Describe the bug**
Rocket Jumper as of 07.04.2022 doesn't work in the tests I had. It creates no knockback at all, but produces standard rocket explosion.

**To Reproduce**
1. Go to 'any map, I presume'
2. Select Soldier
3. Equip Rocket Jumper

**Expected behavior**
Rocket Jumper has unique muffled down explosion with no gunpowder particles and deals standard knockback to the user.

**Comment by KayaDLX** [comment]
Will be implemented later once we get back to adding custom weapons.
