### ISSUE TITLE
Stickies don't despawn after death

### ISSUE THREAD

**Issue by scroobert** [AmperSoftware/TF-Source-2-Issues#63]
### Describe the bug

When you shoot stickybombs as demoman, and then die, they don't fizzle out.

### To Reproduce

1. Pick demoman
2. Shoot some stickies
3. Die
4. Notice the bombs are still there

### Expected behavior

Bombs should break into pieces upon death

**Comment by MoonlyDays** [comment]
This issue seems to be fixed now. Please retest it in the current backend upload and close the issue if you consider it to be fixed.
