### ISSUE TITLE
Gibs have a chance to cause realistic blood to appear

### ISSUE THREAD

**Issue by scroobert** [AmperSoftware/TF-Source-2-Issues#64]
### Describe the bug

There's a chance that an explosion gib will cause s&box's default blood decal to appear

### To Reproduce

1. Pick any explosive class
2. Shoot an enemy until they gib
3. Notice there's realistic blood

### Expected behavior

TF2's normal cartoony blood should appear

### Media/Files

![image](https://user-images.githubusercontent.com/110732290/183504913-eff79e6e-bdb2-4eb2-94b8-6ace427262da.png)

**Comment by KayaDLX** [comment]
Fixed in the latest master commit.
