### ISSUE TITLE
Velcro-bombs stuck in the sky 

### ISSUE THREAD

**Issue by HichGog** [AmperSoftware/TF-Source-2-Issues#68]
### Describe the bug

When I was playing on playtest, I saw that there were velcro bombs stuck in the sky, on the map "Viaduct" near the Red's spawn
![Uploading 2022-08-15-1.png…]()
![Uploading 2022-08-15_1.png…]()
![Uploading 2022-08-15_1-1.png…]()

### To Reproduce

1. Go to the Viaduct and and take the "Demoman" class
2. take a weapon that shoots velcro-bombs
3. shoot into the sky near Red's spawn and shoot into the sky as in the screenshot

### Expected behavior

velcro bombs should not get stuck in the sky

**Comment by KayaDLX** [comment]
Dup of https://github.com/AmperSoftware/TF-Source-2-Issues/issues/66
