### ISSUE TITLE
Class switch doesn't update upon death

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#7]
**Describe the bug**
If you change your class, you die, but if you, during that death period, select other class to be respawned as, it doesn't update and still spawns you with the first selection.

**To Reproduce**
1. Go to any map
2. Switch class to other, expected to die and wait for respawn
3. While at it, switch class once again to the other 
4. Be respawned as the first selected class instead, not the last one

**Expected behavior**
Class switching should have no delays and no limits at class picking, so it should put the latest picked class as the respawn target.

**Comment by uglycoal** [comment]
UPD: Was tested in Arena mode, might be expected behavior?

**Comment by KayaDLX** [comment]
Arena maps don't have func spawnroom implemented yet.

**Comment by MoonlyDays** [comment]
This issue seems to be fixed now. Please retest it in the current backend upload and close the issue if you consider it to be fixed.
