### ISSUE TITLE
Demoman Sticky Launcher does not reload

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#8]
**Describe the bug**
That's it. It just doesn't.

**To Reproduce**
1. Go to any map
2. Pick Demoman
3. Shoot some stickies
4. Try to reload, it doesn't work

**Expected behavior**
Please reload

**Comment by qualitykk** [comment]
This issue should be fixed now.

**Comment by uglycoal** [comment]
Still kinda buggy, only reloads 1 and only if 1 was shot

https://user-images.githubusercontent.com/41569944/162279934-40587b56-414b-45c7-bd80-a3bedbf66f92.mp4

**Comment by KayaDLX** [comment]
Cannot reproduce, are you sure this is still happening @uglycoal ?

**Comment by uglycoal** [comment]
Old issue. Been fixed a while ago and does work atm.
