### ISSUE TITLE
[Control Point] SetOwner input in Hammer to switch the point owner during runtime.

### ISSUE THREAD

**Issue by yourbadandimbest** [AmperSoftware/TF-Source-2-Issues#87]
### What can't you do?

In Hammer there is no SetOwner input in Hammer that lets you control the owner of a control point at runtime.

### How would you like it to work?

For example I could place a button in the world that when pressed instantly sets the control point to its neutral state to be ready for capturing.

### What have you tried?

In Hammer I can set the default owner at the start of the game but that is not what I am looking for.

**Comment by qualitykk** [comment]
This should be fixed, feel free to close this issue if its fixed in the latest backend upload.

**Comment by yourbadandimbest** [comment]
Can this feature be added again?
