### ISSUE TITLE
Sticky Launcher add view bob

### ISSUE THREAD

**Issue by uglycoal** [AmperSoftware/TF-Source-2-Issues#9]
**Is your feature request related to a problem? Please describe.**
Sticky Launcher has no view bob like Grenade Launcher does, creating a very cheap and static look to shooting sticky bombs.

**Describe the solution you'd like**
Add a similar slight view bob to each sticky shot just like on Grenade Launcher.

**Comment by MoonlyDays** [comment]
Should be fixed when `damage` branch is merged.
