### ISSUE TITLE
Prop_Animated doesn't render in TF:S2 gamemode.

### ISSUE THREAD

**Issue by yourbadandimbest** [AmperSoftware/TF-Source-2-Issues#90]
### Describe the bug

Prop_Dynamic got replaced with Prop_Animated. Prop_animated will not render when using the Team Fortress: Source 2 gamemode.

### To Reproduce

1. Place Prop_Animated with a mesh in the map and compile
3. Set gamemode to TF:S2.
4. The prop will not render ingame.

### Expected behavior

Prop_Animated should render the mesh.

### Media/Files

![1](https://user-images.githubusercontent.com/91832803/190750761-b8938b00-7697-4f59-b5b9-5e6aac07e917.png)
![2](https://user-images.githubusercontent.com/91832803/190750895-460d48b7-dab5-4b97-acb4-2f92d2d13ca8.png)

### Additional context

tf_prop_dynamic does still render, however.

**Comment by KayaDLX** [comment]
Yeah we use `tf_prop_dynamic` in TF:S2 for all gamemode related stuff.
```
/// <summary>
/// Dummy placeholder entity until Facepunch rewrites prop_dynamic in C#.
/// C# and C++ can't interact with each other right now in terms of Hammer I/O system.
/// </summary>

**Comment by yourbadandimbest** [comment]
prop_animated renders now 💀
